### ISSUE TITLE
General status question

### ISSUE THREAD

**Issue by bekozi** [satamas/fortran-plugin#1]
Hello and thank you for working on this! Is this plugin ready for testing?

**Comment by sgshulman** [comment]
Hello! Thank you for your interest.
I think it is not a time for testing yet. Many things should be done.
We are going to develop the plugin now, so I hope it will be ready for testing soon.

**Comment by bekozi** [comment]
Very cool. Let me know. I'm happy to be an early adopter!

**Comment by sgshulman** [comment]
Hello!
We released the plugin first version today. We are ready to receive bug reports now.
https://plugins.jetbrains.com/plugin/9699-fortran

We have many features to be implemented later. We have some ideas, what features to make in the next versions. The nearest plans include formatting and navigation.
