### ISSUE TITLE
editor - structure code sync not working since 2023 update.

### ISSUE THREAD

**Issue by tkgamble** [satamas/fortran-plugin#114]
since updating PyCharm to the 2023 version the code sync between the structure window and the editor window no longer works. Used to be able to select a subroutine in the structure window and have the editor goto that point in the code. Was working in the 2022 version. still works for python code in the 2023 version. This feature is pretty much a necessity these days.

**Comment by tkgamble** [comment]
I searched the outstanding issues, but did not find any specific to this problem.

**Comment by thursdayscoming** [comment]
I have the same issue. Specifically, the "Navigate with Single Click" functionality in the Structure window no longer works for fortran files only. It used to work with fortran files in previous versions, and it still works in non-fortran files. I've tried the repair IDE and invalidate caches options without success.
I am using PyCharm 2023.2.5 for Mac OS (M1).

**Comment by satamas** [comment]
[https://github.com/satamas/fortran-plugin/commit/ff45aaddd40c3f0e8a0630aa18be3fafe3af404d](Fixed)
