### ISSUE TITLE
How to add Fortran to Run/debug configurations of IntelliJ (PyCharm)?

### ISSUE THREAD

**Issue by Desperateprogrammer1** [satamas/fortran-plugin#13]
Hello,
I would like to use IntelliJ (community version) with Fortran plugin to run Fortran.
I managed to import the Fortran plugin somehow but when I want to run a test file in Fortran, I cannot compile/run it:
In the Run/Debug configurations, there are only Python settings. How do I 'add' a Fortran debugger?
(only having imported the Fortran plugin does not seem sufficient to be able to run a Fortran code, and I have no idea how to proceed).
I would be grateful for help.
Thanks!

**Comment by satamas** [comment]
Hi.
Please take a look at my [answer](https://stackoverflow.com/questions/44592395/intellij-plugin-fortran) to the same question on stackowerflow.
