### ISSUE TITLE
the procedure attribute 'non_overridable' can not be recognized correctly.

### ISSUE THREAD

**Issue by sofair** [satamas/fortran-plugin#14]
After searching the source code, I found that this issue is caused by misspelling the word, it should be 'non_overridable' but in the source code it is 'nonoverridable', (tested by ifort and gfortran).

**Comment by sgshulman** [comment]
Hello! Thank you for your report. It should be 'non_overridable' due to standard. This misspelling is fixed now. Next version will work with this keyword in a proper way.
If you note any other issues, please report about them.
