### ISSUE TITLE
The autocompletion of `do` and `if` statement does not works when the block is warped in another block of the same type.  

### ISSUE THREAD

**Issue by sofair** [satamas/fortran-plugin#16]
It's me again ^v^. And sorry for my poor English. 
Sometime, I use loop in anther loop. And I think I'm not alone.  when the same statement is used, the autocompletion of the inner statement does not as expected. The tested commands are `if` and `do`.  Sample code is also provided here.

```
    subroutine print_array_r1()
        implicit none
        integer :: i,j,k
        !Autocompletion works properly
        if(i .eq. 1)then
            do j=1,3
                if(j==2)then
                    do k=1,3
                        print*,i,j,k
                    end do
                end if
            end do
        end if
        !Autocompletion does not works
        if(i .eq. 1)then
            if (j .eq. i)then
            !end if is expected but not show up
        end if
            
        do i=1,2
            do j=1,3
            !end do is expected but not show up   
        end do    

    end subroutine
```

And many thanks to your effort!
sincerely!

**Comment by satamas** [comment]
Hi. 
Thank you for your issues and for your interest to our plugin. Our English is not perfect either, so there is nothing to worry about.
Strictly speaking we are talking not about autocompletion, but about enter handler. It doesn't work for inner cycles because our parser parses them as already completed ones (and outer cycle parsed is incomplete). 
We will try to fix it.

**Comment by sgshulman** [comment]
Thank you for your report. This is our parser feature: it matches inner loop as completed and outer loop as incomplete. I have an idea, how to fix it. I hope, it will be fixed in the next release.

**Comment by sofair** [comment]
I'am using this plugin, it's amazing, thank you very much for your perfect work.
