### ISSUE TITLE
parser error

### ISSUE THREAD

**Issue by sishue** [satamas/fortran-plugin#2]
Dear satamas,

I am very interested in your fortran-plugin project since I am a heavy fortran user.

So I download the source and compile it by myself. Then I did a little test and found that the parser did not work for the following case.

`module test_mod

implicit none

type ty1 !define a class including a procedure
contains
    procedure:: sub => sub1
end type

contains

subroutine sub1(this)
    class(ty1):: this
    print*,"sub1"
end subroutine

subroutine test1()
    type(ty1):: t1
    call t1%sub() !call class procedure; parser error: '%' or '[' expected, got ''
end subroutine

end module`

I hope that this message will help you improve the parser.

Best,
yours

**Comment by sgshulman** [comment]
Dear sishue,

Thank you for your report. I have a small fix for this problem, now the plugin doesn't mark your code as an error. This part of the parser will be also improved later, when we'll work on the code navigation.

To be honest we have limited test base for FORTRAN 2008 with modern features. Please, report about other parsing problems, if you see them.

By the way, we released the first version of the plugin this morning to gain some feedback from users. So we also have an issue tracker on youtrack: https://youtrack.jetbrains.com/issues/FOR    
You can use it too.

Thank you for your interest and report

**Comment by sishue** [comment]
Dear satamas,

Thank you very much for this lightning fast response.  I will keep using the plugin and reporting problems.

Looking forward to the full features of the plugin, e.g., code assistant, code folding, and etc.

Best,
yours
