### ISSUE TITLE
Clion hesitate this error, when start to debug the program.

### ISSUE THREAD

**Issue by sofair** [satamas/fortran-plugin#22]
Platform: Windows Server 2008R2
Clion Version: 2017.3.1
Plugin Version: 2017.3.4

```
Error during pretty printers setup: Error while executing Python code.

Some features and performance optimizations will not be available.

python import sys; sys.path.insert(0, "D:/Users/user/.CLion2017.3/config/plugins/fortran-plugin/classes/gdb/renderers"); from default.printers import register_default_printers; register_default_printers(None); from libstdcxx.v6.printers import register_libstdcxx_printers; register_libstdcxx_printers(None); 
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named default.printers
Error while executing Python code.
```

**Comment by satamas** [comment]
Have you tried to debug c/c++ with CLion on this machine?
Why I'm asking: we've put pretty printers file to our plugin, but in fact this is a copy of pretty printers file from CLion with important fix for Fortran. So I think, that you will face the same error if you will try to debug c/c++.

**Comment by satamas** [comment]
In fact we don't even need c/c++ code. Can you just try to debug your program with default Run Configuration, not ours and see what will happen, will the error be printed, or not.

**Comment by sofair** [comment]
Hi satamas, I debuged a hello_world c code with default configuration. It does not output any error message. I also tryed debug hello fortran code with default configuration, it also does not hesitate any error message(did not pause at break points). But, debug with new fortran configuration, the reported error message came again.

**Comment by satamas** [comment]
I've found problem, will fix it today

**Comment by satamas** [comment]
Fixed in all branches.

**Comment by qiujiangkun** [comment]
It still happens in my machine

**Comment by kaboussi** [comment]
The error is still on
ArchLinux
Clion 2023.1.3
