### ISSUE TITLE
parser error2

### ISSUE THREAD

**Issue by sishue** [satamas/fortran-plugin#3]
Dear satamas,

I found a F77 parser error as following:

`module test_mod2
implicit none

double complex:: var1 !parser error: '(', ':', '=', '=>' or precision expected, got 'complex'

end module`

Best, 
yours

**Comment by sgshulman** [comment]
Glad to see you again!

As I understand, "double complex" is an extension to the standard. Standard types are character, integer, real, complex, logical, and double precision. I will add more non standard types soon.

Best wishes,
Sergei

**Comment by sishue** [comment]
Dear Sergei,

For your consideration, I actually tested "double complex" according to the BLAS library: [http://www.netlib.org/lapack/lapack-3.1.1/html/dcabs1.f.html](url)

Best,
Sishue

**Comment by sgshulman** [comment]
Dear sishue, 

we try to work with the standard first of all. There are a lot of non standard extensions to Fortran. We implemented some of them, about which I know, that people use them and we can support them easily. 

So, the idea is very easy: you tell us, what non standard extensions you really need and use. We try to support them too.

You need "double complex". We will support it.

**Comment by sishue** [comment]
Dear Sergei,

Thank you very much for this active response.

Using the plugin, I will keep working on the code I am familiar with. Hope to communicate with you again.

Best, 
Sishue

**Comment by sgshulman** [comment]
Double complex type is added into the branch "v1_fixes", which collects fixes to the first version of the plugin.

Ready for a new issue ;)

Best wishes,
Sergei
