### ISSUE TITLE
Code Completion

### ISSUE THREAD

**Issue by Libavius** [satamas/fortran-plugin#31]
Atm, there is no code completion for Fortran. Will code completion be added to this plugin? 
Of course intelligent code completion, that knows scope and type and everything would be wonderful.
But I'd also prefer stupid code completion - that simply suggests all strings found in the code (as in text editors like sublime) - over no completion at all.

In any case: thanks for the great plugin!

Best
Libavius

**Comment by satamas** [comment]
Yes, I'll add it soon and it would be much smarter then just text completion. It's not implemented yet just because of lack of time to develop this plugin, but I'll really try to find some, because I see that plugin is used.

**Comment by satamas** [comment]
I've added code completion. It's far from perfect, but better then text completion.
