### ISSUE TITLE
IDE fatal error

### ISSUE THREAD

**Issue by Gerardwx** [satamas/fortran-plugin#34]
CLion 2018.2.2
Build #CL-182.4129.51 built Aug 22, 2018
JRE 1.8.0_152-release-1248-b8 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
[induced.txt](https://github.com/satamas/fortran-plugin/files/2364337/induced.txt)
[stacktrace.txt](https://github.com/satamas/fortran-plugin/files/2364338/stacktrace.txt)

**Comment by satamas** [comment]
Thanks for report and sorry for not responding for a long time. I've fixed the issue
