### ISSUE TITLE
Unable to process the associate keyword

### ISSUE THREAD

**Issue by smillerc** [satamas/fortran-plugin#37]
This plugin seems to struggle with the `associate` block, like one in the following snippet. 

```fortran
program associateTest
  implicit none
  integer :: a=1,b=1
  associate( x => a*b )
    print *, x                ! yields: 1
    a=10
    print *, x                ! yields: 1
  end associate
end program associateTest
```
It produces the following errors at ` associate(` and highlights the leading `(`
```
ERROR '%', '(', ':', '[' or identifier expected, got '(' 
ERROR '%', '(', ':', , , , , , '[', eol, identifier or integerliteral expected, got '(' 
```

Other than this, I absolutely love this plugin! So thank you for creating and maintaining it!

**Comment by dryabov** [comment]
I may be mistaken, but it looks like commas are missed in `FortranParser.bnf` for `associate_stmt`, and the correct statement should be

    associate_stmt ::= label_decl? construct_name_decl? associate_ '(' <<list association>> ')' { pin = 3 }

**Comment by satamas** [comment]
@smillerc thanks for issue, I've fixed it and pubished a new version.
@dryabov you are abolutely right, thanks.
