### ISSUE TITLE
syntax error in code complete for the associate block

### ISSUE THREAD

**Issue by smillerc** [satamas/fortran-plugin#38]
There is a minor spelling error here that shows up in the associate block tab completion. It should be `"associate"` rather than `"asociate"`

https://github.com/satamas/fortran-plugin/blob/40a7fadaf9ca0ac6072c2f3b92a6a0426a04e87e/src/main/kotlin/org/jetbrains/fortran/lang/psi/ext/FortranExecutableConstruct.kt#L39

Once again, thanks for maintaining this fantastic plugin! I use it daily.

**Comment by satamas** [comment]
Sorry for delay. I've fixed this and published plugin update
