### ISSUE TITLE
GDB and LLDB not working

### ISSUE THREAD

**Issue by fmilicchio** [satamas/fortran-plugin#39]
Hi,

I've installed the latest plugin on CLion 2019.1, and I've noticed that variables are not available in the debugger.

If I use the standard LLDB I can debug, stepping into functions, however, I am unable to see variables [as you can see from the screenshot](https://imgur.com/NxxILz2).

If I switch to GDB, I have the following error:

```
BFD: /Users/.../Desktop/untitled/cmake-build-debug-gdb/untitled: unknown load command 0x32
BFD: /Users/.../Desktop/untitled/cmake-build-debug-gdb/untitled: unknown load command 0x32
com.jetbrains.cidr.execution.debugger.backend.gdb.GDBDriver$GDBCommandException: "/Users/.../Desktop/untitled/cmake-build-debug-gdb/untitled": not in executable format: File format not recognized

Process finished with exit code 0
```

The program has been compiled and works, running from the console works:

```
% file Desktop/untitled/cmake-build-debug-gdb/untitled
Desktop/untitled/cmake-build-debug-gdb/untitled: Mach-O 64-bit executable x86_64

% Desktop/untitled/cmake-build-debug-gdb/untitled 
 Hello, World!            0
```

Am I missing something in my project configuration?

Thanks!

**Comment by satamas** [comment]
I can fix your issue with missing variables by initializing i in code like this:
```
program untitled
    integer :: i = 0
    write(*, *) "Hello, World!", i
end program
```

Talking about GDB and LLDB it sounds strange because as far as I know, it's not easy to use LLDB+Fortran. So I wouldn't be surprised to opposite situation when everything works for GDB but not for LLDB, but your case sounds really strange
