### ISSUE TITLE
Predefined preprocessor macros break syntax highlighting

### ISSUE THREAD

**Issue by bekozi** [satamas/fortran-plugin#4]
`__LINE__` and `__FILE__` causing issues (I think).

![screenshot from 2017-05-15 10-31-29](https://cloud.githubusercontent.com/assets/636921/26068194/f168616e-3959-11e7-8a7a-e8d974763277.png)

There may also be issues with `#ifdef`s. Here is an example Fortran file that triggers the issue: https://gist.github.com/bekozi/044a8b92fd238c4ee3d05035f3401a97#file-esmf_devlognetcdferror-f90-L16.

Using version `1.0`!

**Comment by sgshulman** [comment]
Hello! Thank you for your issue.

It is one more case when real code doesn't hold standard. According to standard name starts with a letter (not an underscore). I can add an opportunity to start names from an underscore (as we have such things in the real code), but I should check that this won't make other problems. I will also try to upgrade the parser not to mark all text after such errors as a bad character.

All preprocessor directives should be parsed as a line without any specific behaviour. Preprocessor is also a non standard thing, so we decided to have very simple parser for it now. We are going to add good preprocessor parser in the future.

**Comment by bekozi** [comment]
> Hello! Thank you for your issue.

No problem. :smile:

> It is one more case when real code doesn't hold standard.

Isn't that the truth...

> All preprocessor directives should be parsed as a line without any specific behaviour. Preprocessor is also a non standard thing, so we decided to have very simple parser for it now. We are going to add good preprocessor parser in the future.

No rush of course. I'll be happy to test anything as it develops.

**Comment by satamas** [comment]
There is one problem with preprocessor: it's already implemented in CLion. That means that support of preprocessor in our plugin will most probably be available in CLion only. 
So it looks reasonable to support general IntelliJ features first and than add cool CLion-specific features, including preprocessor, debugger, e.t.c.

**Comment by sgshulman** [comment]
bekozi, the parser with the last fix finds no errors in your code. One more non standard extension is added (dollar sign in names).

satamas, I'm afraid, we'll spend a lot of time to have good inspections of the code.

**Comment by bekozi** [comment]
I can confirm this works in CLion. Sorry for the delay in testing... Excellent work! I'll close the ticket as I think a different tracker is preferred.
