### ISSUE TITLE
Suppoprt for LLDB debugger under macOS

### ISSUE THREAD

**Issue by togop** [satamas/fortran-plugin#48]
In macOS Mojave there are some problems with the apparently supported GDB debugger (as mentioned by JetBrains) and is not working for me at all.
Surprisingly, the LLDB debugger is almost working and I can go to a breakpoint and do steps but evaluating variables and expressions is not working at all.
It will be nice if at least one of these debugger is working under macOS and evaluating is working.

**Comment by satamas** [comment]
Hi. 
Debugger is provided by CLion itself, I only enable it for Fortran in plugin. Therefore such kind of issues should go to [CLion issue tracker](https://youtrack.jetbrains.com/issues/CPP).
