### ISSUE TITLE
interface operator(/) not correctly parsed

### ISSUE THREAD

**Issue by sgeard** [satamas/fortran-plugin#61]
This statement is marked as an error (red squiggly line) and thereafter the formatting is wrong. Other operators are parsed correctly, e.g.
interface operator(*)

**Comment by satamas** [comment]
It happens because `(/` is parsed as single token. It is useful for arrays declarations. Will drop this oken and think how it can be replaced

**Comment by sgeard** [comment]
Thanks for the info. I've now changed my code to
`interface operator( / )`
and that parses correctly.
