### ISSUE TITLE
file extension should be .f90, not .f95

### ISSUE THREAD

**Issue by jzwolak** [satamas/fortran-plugin#8]
.f95 is not the standard file extension for free form fortran source. In fact, there is no standard really, but the accepted extension is .f90 and some compilers will not accept .f95 (like Intel's compiler).

This plugin creates new fortran files with the extension .f95. It should be .f90.

**Comment by sgshulman** [comment]
Hello! Thank you for your issue! Indeed, there are no standard extensions for Fortran files. It was .f95 because I like how .f95 looks. Now we have a reason to use .f90. I think, new version will use .f90 extension. I hope it will be realized on Monday or Tuesday.

**Comment by jzwolak** [comment]
Great! Thanks.

--
Jason Zwolak
