### ISSUE TITLE
Support for 2022.03

### ISSUE THREAD

**Issue by llinfrance** [satamas/fortran-plugin#88]
Hello,
Thank you for your great plugin. By any chance, do you intent to support the new version of IntelliJ IDEA 2022.03 ?
Best

**Comment by satamas** [comment]
Hi.

**Comment by llinfrance** [comment]
Yes indeed !
Sorry for the opened issue... This morning, the soft did not ask for the update, and when looking here I did see the update.
Thank again for your work
